### ISSUE TITLE
Extracting all the sentences with URLs

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/Aztec_Pub_Classifier#13]
Include context as well

**Comment by vincekyi** [comment]
Creating a regex to get URLs

**Comment by koallison** [comment]
Things to note:
- URLs don't always have http(s)/ftp/www
- because of PDF formatting, when converted using pdftotext there are newlines in awkward places, sometimes between words, sometimes in the middle of a URL
- Sometimes there is more text after the references section
